In [0]:
#type code here
!pwd

/Users/padmapolashpaul/Desktop/mlos/draft/ipynb_mlos



In [0]:
# # install
# !pip3 install --upgrade pip
# !pip3 install tensorflow
# ! pip3 install keras
# ! pip3 install --upgrade keras
# !pip3 freeze
!pwd


/Users/padmapolashpaul/wp/mos/ppaul_braintoy.ai/ff37ca2140bf4238842453af5ce3fc59/models/custa/idcusta50/app



In [0]:
#https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics
#pip3 install sklearn
# df is our dataframe
# 1. Load data 
# 2. create input and target list
# 3 cross-validation Dataset
# 4. Modeling 
# 1. Load data 
import pandas as pd
import pickle 
# Way one
# from sklearn import model_selection
# model_selection.train_test_split()
from sklearn.model_selection import train_test_split


df=pd.read_csv("irish.csv",encoding="UTF-8",low_memory=False)
# 2. create input and target list
inpfeatures=['sepal-length', 'sepal-width', 'petal-length', 'petal-width']
target=  ['species']
X = df[inpfeatures]
y= df[target]
ts=0.2
# 3. cross-validation Dataset 80/20 split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=ts)


# fn="tst_data.pkl"
# with open(fn,'wb') as writebuf:
#     pickle.dump(X_test, writebuf)
# fn="tst_lbl.pkl"
# with open(fn,'wb') as writebuf:
#     pickle.dump(y_test, writebuf)

    
    
# from sklearn.neighbors import  KNeighborsClassifier
# from sklearn.svm import LinearSVR 
# model = LinearSVR()
# model.fit(X_train,y_train.values.ravel())
    





In [0]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.utils import to_categorical
# https://numpy.org/doc/stable/reference/generated/numpy.unique.html
# print(y_train)
# print(df["species"].to_numpy)
def my_ohe(col_as_df_col):
    myarray=col_as_df_col.to_numpy()
    uniques, ids= np.unique(myarray,return_inverse=True)
    return to_categorical(ids, len(uniques))

train_y_ohe= my_ohe(y_train)
print(train_y_ohe)

test_y_ohe= my_ohe(y_test)

print(train_y_ohe)

print(test_y_ohe)

# print(train_y_ohe)

# a, b = train_y_ohe.shape

# print(a)
# print(b)


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1.

In [0]:
# model = tf.keras.models.Sequential(
#     [
#   tf.keras.layers.Flatten(input_shape=(4, 1)),
#   tf.keras.layers.Dense(3, activation='relu'),
#   tf.keras.layers.Dense(6, activation='relu'),
#   tf.keras.layers.Dense(4, activation='relu'),
#   tf.keras.layers.Dropout(0.2),
#   tf.keras.layers.Dense(1)
# ]
# )

model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3)
])

model.summary()

model.compile(optimizer='adam',loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), metrics=['accuracy'])


# xTrn=tf.convert_to_tensor(X_train.values)

# print(xTrn)

# # print(X_train)
# model.compile(optimizer='adam', metrics=['accuracy'])

# model.fit( xTrn, train_y_ohe, epochs=1)


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________



In [0]:

model.fit( X_train, train_y_ohe, epochs=1)

4/4 [==============================] - 0s 1ms/step - loss: 0.7344 - accuracy: 0.6000



In [0]:
#type code here
itm_pred=model.predict(X_test)
print(itm_pred)

pclass= np.argmax(itm_pred, axis=1)

print(pclass)


[[ 0.13833919 -0.4917107   0.55035406]
 [ 0.23638955 -0.4840313   0.6801201 ]
 [ 0.2023099  -0.39123574  0.50585365]
 [ 0.5662303   0.14362514  0.39128968]
 [ 0.23893094 -0.34638378  0.52303344]
 [-0.05732018 -0.81531173  0.6498045 ]
 [ 0.4217643  -0.18569084  0.5798623 ]
 [ 0.37887195 -0.12481782  0.4792189 ]
 [ 0.54249996  0.01861513  0.46252394]
 [-0.08574536 -0.7788773   0.5914874 ]
 [ 0.36204806 -0.16720493  0.49203885]
 [ 0.09240008 -0.503099    0.5084695 ]
 [ 0.48649347 -0.12106597  0.58053553]
 [ 0.31370708 -0.22336258  0.51049435]
 [ 0.72957957  0.2855641   0.33593705]
 [ 0.37854332 -0.12204875  0.5518423 ]
 [ 0.71269333  0.27370834  0.36439443]
 [ 0.15028626 -0.47612336  0.5762256 ]
 [ 0.7040747   0.21048622  0.37984908]
 [-0.01124616 -0.6474705   0.53323156]
 [ 0.3662696  -0.19668297  0.5256975 ]
 [ 0.2510821  -0.25202453  0.4436669 ]
 [ 0.70730984  0.17779794  0.41610456]
 [ 0.658134    0.15657578  0.39483923]
 [ 0.1765414  -0.4225352   0.5605521 ]
 [ 0.02428986 -0.5723369 

In [0]:
#type code here
itm_pred=model.predict(X_test)
print(itm_pred)

pclass= np.argmax(itm_pred, axis=1)

print(pclass)


[[ 0.13833919 -0.4917107   0.55035406]
 [ 0.23638955 -0.4840313   0.6801201 ]
 [ 0.2023099  -0.39123574  0.50585365]
 [ 0.5662303   0.14362514  0.39128968]
 [ 0.23893094 -0.34638378  0.52303344]
 [-0.05732018 -0.81531173  0.6498045 ]
 [ 0.4217643  -0.18569084  0.5798623 ]
 [ 0.37887195 -0.12481782  0.4792189 ]
 [ 0.54249996  0.01861513  0.46252394]
 [-0.08574536 -0.7788773   0.5914874 ]
 [ 0.36204806 -0.16720493  0.49203885]
 [ 0.09240008 -0.503099    0.5084695 ]
 [ 0.48649347 -0.12106597  0.58053553]
 [ 0.31370708 -0.22336258  0.51049435]
 [ 0.72957957  0.2855641   0.33593705]
 [ 0.37854332 -0.12204875  0.5518423 ]
 [ 0.71269333  0.27370834  0.36439443]
 [ 0.15028626 -0.47612336  0.5762256 ]
 [ 0.7040747   0.21048622  0.37984908]
 [-0.01124616 -0.6474705   0.53323156]
 [ 0.3662696  -0.19668297  0.5256975 ]
 [ 0.2510821  -0.25202453  0.4436669 ]
 [ 0.70730984  0.17779794  0.41610456]
 [ 0.658134    0.15657578  0.39483923]
 [ 0.1765414  -0.4225352   0.5605521 ]
 [ 0.02428986 -0.5723369 

In [0]:
#type code here
itm_pred=model.predict(X_test)
print(itm_pred)

pclass= np.argmax(itm_pred, axis=1)

print(pclass)


[[ 0.13833919 -0.4917107   0.55035406]
 [ 0.23638955 -0.4840313   0.6801201 ]
 [ 0.2023099  -0.39123574  0.50585365]
 [ 0.5662303   0.14362514  0.39128968]
 [ 0.23893094 -0.34638378  0.52303344]
 [-0.05732018 -0.81531173  0.6498045 ]
 [ 0.4217643  -0.18569084  0.5798623 ]
 [ 0.37887195 -0.12481782  0.4792189 ]
 [ 0.54249996  0.01861513  0.46252394]
 [-0.08574536 -0.7788773   0.5914874 ]
 [ 0.36204806 -0.16720493  0.49203885]
 [ 0.09240008 -0.503099    0.5084695 ]
 [ 0.48649347 -0.12106597  0.58053553]
 [ 0.31370708 -0.22336258  0.51049435]
 [ 0.72957957  0.2855641   0.33593705]
 [ 0.37854332 -0.12204875  0.5518423 ]
 [ 0.71269333  0.27370834  0.36439443]
 [ 0.15028626 -0.47612336  0.5762256 ]
 [ 0.7040747   0.21048622  0.37984908]
 [-0.01124616 -0.6474705   0.53323156]
 [ 0.3662696  -0.19668297  0.5256975 ]
 [ 0.2510821  -0.25202453  0.4436669 ]
 [ 0.70730984  0.17779794  0.41610456]
 [ 0.658134    0.15657578  0.39483923]
 [ 0.1765414  -0.4225352   0.5605521 ]
 [ 0.02428986 -0.5723369 

In [0]:
#type code here
itm_pred=model.predict(X_test)
print(itm_pred)

pclass= np.argmax(itm_pred, axis=1)

print(pclass)


[[ 0.13833919 -0.4917107   0.55035406]
 [ 0.23638955 -0.4840313   0.6801201 ]
 [ 0.2023099  -0.39123574  0.50585365]
 [ 0.5662303   0.14362514  0.39128968]
 [ 0.23893094 -0.34638378  0.52303344]
 [-0.05732018 -0.81531173  0.6498045 ]
 [ 0.4217643  -0.18569084  0.5798623 ]
 [ 0.37887195 -0.12481782  0.4792189 ]
 [ 0.54249996  0.01861513  0.46252394]
 [-0.08574536 -0.7788773   0.5914874 ]
 [ 0.36204806 -0.16720493  0.49203885]
 [ 0.09240008 -0.503099    0.5084695 ]
 [ 0.48649347 -0.12106597  0.58053553]
 [ 0.31370708 -0.22336258  0.51049435]
 [ 0.72957957  0.2855641   0.33593705]
 [ 0.37854332 -0.12204875  0.5518423 ]
 [ 0.71269333  0.27370834  0.36439443]
 [ 0.15028626 -0.47612336  0.5762256 ]
 [ 0.7040747   0.21048622  0.37984908]
 [-0.01124616 -0.6474705   0.53323156]
 [ 0.3662696  -0.19668297  0.5256975 ]
 [ 0.2510821  -0.25202453  0.4436669 ]
 [ 0.70730984  0.17779794  0.41610456]
 [ 0.658134    0.15657578  0.39483923]
 [ 0.1765414  -0.4225352   0.5605521 ]
 [ 0.02428986 -0.5723369 